server:
  port: 8080 #端口号

spring:
  datasource:
    password: 217812.com #数据库用户名
    username: root #数据库密码
    #springboot-common需要切换为对应数据库
    url: jdbc:mysql://localhost:3306/springboot-common?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: application #项目名称
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER





